name: CI
run-name: Run linter and unit tests
on: [ push ]
jobs:
  lint-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
